engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
languages:
  JavaScript: true
  Python: true
exclude_paths:
- "example_app"
- "flask_jsondash/static/js/vendor"
