test:
    pytest tests
sudo: false
python:
  - "2.7"
  - "3.5"
language: python
cache:
  pip
notifications:
  email:
    recipients:
      - dxdstudio@gmail.com
    on_failure: always
    on_success: always
install:
    - pip install -U tox
    - pip install -U pytest
    - pip install -U pyquery
    - python setup.py install
script: tox
